# Generated by Django 3.0.3 on 2020-04-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Performer')),
            ],
        ),
    ]
