# Generated by Django 3.0.3 on 2020-04-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='performer',
        ),
        migrations.AddField(
            model_name='program',
            name='performer',
            field=models.ManyToManyField(to='index.Performer'),
        ),
    ]
